"""
Canonical Signal model — every source is normalised into this schema (HTML §4).

Field mapping to HTML canonical schema:
    id              → signal_id   (uuid-v4 generated by ingestion layer)
    timestamp       → timestamp
    source          → source      (cloudwatch_metrics | application_logs | grafana_alerts)
    environment     → environment
    service         → service
    component       → component
    type            → signal_type (metric_anomaly | error_log_burst | grafana_alert)
    anomaly_score   → anomaly_score (0.0–1.0, computed by detection layer)
    evidence        → evidence    (PII-free summary text)
    metadata        → metadata    (source-specific extras)

Legacy compatibility fields (used by detection helpers and kept for backward compat):
    value           optional raw numeric for metric signals
    template_id     optional Drain3 cluster id for log signals
    message         raw message text (DEPRECATED — use evidence; kept for ingestion transition)
"""
from pydantic import BaseModel, Field
from typing import Any, Optional
from datetime import datetime


class Signal(BaseModel):
    # ── Core canonical fields (HTML §4) ─────────────────────────────────────
    id: str
    timestamp: datetime

    source: str          # cloudwatch_metrics | application_logs | grafana_alerts
    environment: str     # prod | staging | dev
    region: str = "unknown"

    service: str
    component: str

    type: str            # metric_anomaly | error_log_burst | grafana_alert

    # Computed by detection layer — 0.0 = normal, 1.0 = maximally anomalous
    anomaly_score: float = 0.0

    # PII-free evidence string (template text, alarm description, etc.)
    evidence: str = ""

    # Free object for source-specific extras downstream stages need
    metadata: dict[str, Any] = Field(default_factory=dict)

    # ── Legacy / detection-helper fields (not renamed to avoid breaking Member 1) ──
    value: Optional[float] = None        # raw metric value for z-score computation
    template_id: Optional[str] = None   # Drain3 template cluster id
    message: Optional[str] = None       # raw message (pre-redaction staging; use evidence)