"""
Canonical Signal model — every source is normalised into this schema (HTML §4).

Field mapping to HTML canonical schema:
    signal_id / id  → uuid-v4 generated by ingestion layer
    timestamp       → timestamp (ISO-8601 UTC)
    source          → source (cloudwatch_metrics | application_logs | grafana_alerts)
    environment     → environment (prod | staging | dev)
    region          → region (ap-south-1 | us-east-1)
    service         → service
    component       → component
    signal_type/type→ signal_type (metric_anomaly | error_log_burst | grafana_alert)
    anomaly_score   → anomaly_score (0.0–1.0, computed by detection layer)
    evidence        → evidence (PII-free summary text)
    metadata        → metadata (source-specific extras)

Legacy / detection-helper fields:
    value           optional raw numeric for metric signals
    template_id     optional Drain3 cluster id for log signals
    message         message text (synced with evidence)
"""
from datetime import datetime
from typing import Any, Optional
import uuid
from pydantic import BaseModel, ConfigDict, Field, model_validator


class Signal(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="allow")

    # ── Core canonical fields (HTML §4) ─────────────────────────────────────
    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    id: Optional[str] = None
    timestamp: datetime

    source: str          # cloudwatch_metrics | application_logs | grafana_alerts
    environment: str     # prod | staging | dev
    region: str = "ap-south-1"

    service: str
    component: str

    signal_type: str = "metric_anomaly"
    type: Optional[str] = None

    # Computed by detection layer — 0.0 = normal, 1.0 = maximally anomalous
    anomaly_score: float = 0.0

    # PII-free evidence string (template text, alarm description, etc.)
    evidence: str = ""
    message: Optional[str] = None

    # Free object for source-specific extras downstream stages need
    metadata: dict[str, Any] = Field(default_factory=dict)

    # ── Legacy / detection-helper fields ──
    value: Optional[float] = None        # raw metric value for z-score computation
    template_id: Optional[str] = None   # Drain3 template cluster id

    @model_validator(mode="before")
    @classmethod
    def _sync_fields_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            # Sync id and signal_id
            if "id" in d and d["id"] is not None:
                if "signal_id" not in d or d["signal_id"] is None:
                    d["signal_id"] = str(d["id"])
            elif "signal_id" in d and d["signal_id"] is not None:
                d["id"] = str(d["signal_id"])

            # Sync type and signal_type
            if "type" in d and d["type"] is not None:
                if "signal_type" not in d or d["signal_type"] is None:
                    d["signal_type"] = str(d["type"])
            elif "signal_type" in d and d["signal_type"] is not None:
                d["type"] = str(d["signal_type"])

            # Sync message and evidence
            if "message" in d and d["message"] is not None:
                if "evidence" not in d or not d["evidence"]:
                    d["evidence"] = str(d["message"])
            elif "evidence" in d and d["evidence"]:
                if "message" not in d or d["message"] is None:
                    d["message"] = str(d["evidence"])

            return d
        return data

    @model_validator(mode="after")
    def _sync_fields_after(self) -> "Signal":
        if self.id is None:
            self.id = self.signal_id
        if self.type is None:
            self.type = self.signal_type
        if self.message is None and self.evidence:
            self.message = self.evidence
        if not self.evidence and self.message:
            self.evidence = self.message
        return self


# Canonical alias
CanonicalSignal = Signal
